import os
import datetime

def save_document(response_text:str, directory:str = "./outputs"):
    """
    Saves the response text to a document in the specified directory.

    Args:
        response_text (str): The text to be saved in the document.
        direcctory (str): The directory where the document will be saved. Defaults to "./outputs".

    Returns:
        str: The path to the saved document.
    """
    os.makedirs(directory, exist_ok=True)
     # Create markdown content with metadata header
    markdown_content = f"""# 🌍 AI Travel Plan

    # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
    # **Created by:** Atriyo's Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
    """
    try:
        # Write to markdown file with UTF-8 encoding
        # Generate timestamp-based filename
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.md"

        print(filename)

        with open(filename, "w", encoding="utf-8") as file:
            file.write(markdown_content)
        
        print(f"Document saved successfully at {filename}")
        return filename
    except Exception as e:
        print(f"Error saving document: {e}")
        return None
